language: perl

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

install:
  - cpanm --quiet --notest --skip-satisfied XML::Simple Net::Fritz
  - cpanm --quiet --notest --skip-satisfied Test::BDD::Cucumber Expect XML::Simple Class::Tiny
  - rm -rf fritz

script:
  - pherkin -t ~@in_progress 
  - pherkin -t @in_progress || true
  
