language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - cpanm --quiet --notest --skip-satisfied XML::Simple
  - cpanm --quiet --notest --skip-satisfied Test::BDD::Cucumber Expect XML::Simple
  - rm -rf fritz

script:
  - pherkin -t ~@in_progress 
  - pherkin -t @in_progress || true
  